development:
  adapter: postgresql
  database: note_manager_development
  pool: 5
  timeout: 5000
  username: joshnelson

test:
  adapter: postgresql
  database: note_manager_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: note_manager_production
  pool: 5
  timeout: 5000